
export const GET_PUBLIC_DATA = 'GET_PUBLIC_DATA'
export const GET_PUBLIC_DATA_SUCCESS = 'GET_PUBLIC_DATA_SUCCESS'
export const GET_PUBLIC_DATA_FAILURE = 'GET_PUBLIC_DATA_FAILURE'


export const ADD_PUBLIC_DATA = 'ADD_PUBLIC_DATA'
export const ADD_PUBLIC_DATA_SUCCESS = 'ADD_PUBLIC_DATA_SUCCESS'
export const ADD_PUBLIC_DATA_FAILURE = 'ADD_PUBLIC_DATA_FAILURE'


export const UPDATE_PUBLIC_DATA = 'UPDATE_PUBLIC_DATA'
export const UPDATE_PUBLIC_DATA_SUCCESS = 'UPDATE_PUBLIC_DATA_SUCCESS'
export const UPDATE_PUBLIC_DATA_FAILURE = 'UPDATE_PUBLIC_DATA_FAILURE'


export const DELETE_PUBLIC_DATA = 'DELETE_PUBLIC_DATA'
export const DELETE_PUBLIC_DATA_SUCCESS = 'DELETE_PUBLIC_DATA_SUCCESS'
export const DELETE_PUBLIC_DATA_FAILURE = 'DELETE_PUBLIC_DATA_FAILURE'


